[{"sample name": "Create circle by center and radius API Sample", "sample url": "https://help.autodesk.com/cloudhelp/ENU/Fusion-360-API/files/CircleByCenterRadius_Sample.htm", "sample code": "import adsk.core, adsk.fusion, traceback\n\ndef run(context):\n    ui = None\n    try:\n        app = adsk.core.Application.get()\n        ui = app.userInterface\n        \n        doc = app.documents.add(adsk.core.DocumentTypes.FusionDesignDocumentType)\n        \n        design = app.activeProduct\n\n        # Get the root component of the active design.\n        rootComp = design.rootComponent\n\n        # Create a new sketch on the xy plane.\n        sketches = rootComp.sketches\n        xyPlane = rootComp.xYConstructionPlane\n        sketch = sketches.add(xyPlane)\n\n        # Draw some circles.\n        circles = sketch.sketchCurves.sketchCircles\n        circle1 = circles.addByCenterRadius(adsk.core.Point3D.create(0, 0, 0), 2)\n        circle2 = circles.addByCenterRadius(adsk.core.Point3D.create(8, 3, 0), 3)\n\n        # Add a circle at the center of one of the existing circles.\n        circle3 = circles.addByCenterRadius(circle2.centerSketchPoint, 4)\n    except:\n        if ui:\n            ui.messageBox('Failed:\n{}'.format(traceback.format_exc()))"}, {"sample name": "Create Circle By 3 Tangents API Sample", "sample url": "https://help.autodesk.com/cloudhelp/ENU/Fusion-360-API/files/CreateCcircleBy3Tangents_Sample.htm", "sample code": "import adsk.core, adsk.fusion, traceback\n\ndef run(context):\n    ui = None\n    try: \n        app = adsk.core.Application.get()\n        ui = app.userInterface\n\n        doc = app.documents.add(adsk.core.DocumentTypes.FusionDesignDocumentType)\n        design = app.activeProduct\n\n        # Get the root component of the active design.\n        rootComp = design.rootComponent\n\n        # Create a new sketch on the xy plane.\n        sketches = rootComp.sketches;\n        xyPlane = rootComp.xYConstructionPlane\n        sketch = sketches.add(xyPlane)\n\n        # Draw three lines.\n        lines = sketch.sketchCurves.sketchLines;\n        line1 = lines.addByTwoPoints(adsk.core.Point3D.create(0, 0, 0), adsk.core.Point3D.create(3, 1, 0))\n        line2 = lines.addByTwoPoints(adsk.core.Point3D.create(4, 3, 0), adsk.core.Point3D.create(2, 4, 0))\n        line3 = lines.addByTwoPoints(adsk.core.Point3D.create(-1, 0, 0), adsk.core.Point3D.create(0, 4, 0))\n\n        # Draw circle tangent to the lines.\n        circles = sketch.sketchCurves.sketchCircles\n        circle1 = circles.addByThreeTangents(line1, line2, line3, adsk.core.Point3D.create(0,0,0))\n\n        # Apply tangent contstraints to maintain the relationship.\n        constraints = sketch.geometricConstraints\n        constraints.addTangent(circle1, line1)\n        constraints.addTangent(circle1, line2)\n        constraints.addTangent(circle1, line3)\n    except:\n        if ui:\n            ui.messageBox('Failed:\n{}'.format(traceback.format_exc()))"}, {"sample name": "API Sample that demonstrates creating sketch lines in various ways.", "sample url": "https://help.autodesk.com/cloudhelp/ENU/Fusion-360-API/files/CreateSketchLines_Sample.htm", "sample code": null}, {"sample name": "Project To Surface API Sample", "sample url": "https://help.autodesk.com/cloudhelp/ENU/Fusion-360-API/files/ProjectToSurface_Sample.htm", "sample code": null}, {"sample name": "Sketch Chamfer API Sample", "sample url": "https://help.autodesk.com/cloudhelp/ENU/Fusion-360-API/files/SketchChamferSample_Sample.htm", "sample code": null}, {"sample name": "Sketch fillet and offset API Sample", "sample url": "https://help.autodesk.com/cloudhelp/ENU/Fusion-360-API/files/SketchFilletAndOffset_Sample.htm", "sample code": null}, {"sample name": "Sketch Intersect API Sample", "sample url": "https://help.autodesk.com/cloudhelp/ENU/Fusion-360-API/files/SketchIntersect_Sample.htm", "sample code": null}, {"sample name": "Sketch Point API Sample", "sample url": "https://help.autodesk.com/cloudhelp/ENU/Fusion-360-API/files/SketchPointSample_Sample.htm", "sample code": null}, {"sample name": "Sketch Sample API Sample", "sample url": "https://help.autodesk.com/cloudhelp/ENU/Fusion-360-API/files/SketchSample_Sample.htm", "sample code": null}, {"sample name": "Sketch spline through points creation and relative functions API Sample", "sample url": "https://help.autodesk.com/cloudhelp/ENU/Fusion-360-API/files/SketchSplineThroughPoints_Sample.htm", "sample code": null}, {"sample name": "Sketch Text API Sample", "sample url": "https://help.autodesk.com/cloudhelp/ENU/Fusion-360-API/files/SketchTextSample_Sample.htm", "sample code": null}]